// layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto, Grey_Qo, Dancing_Script } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import MyFooter from "./components/Footer";
import AuthProvider from "./auth/Provider";
// import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

// React Context is unavailable in server components
// Cant use client when exporting Metadata
// make a separate component (AuthPrivider) and wrap with sessionProvider, and make
// that component a client component "use client"

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

const poppins = localFont({
  src: "../public/fonts/poppins-regular-webfont.woff2",
  variable: "--font-poppins",
});

const greyQo = Grey_Qo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-grey-qo",
});

const dance = Dancing_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dance",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={`$ ${roboto.variable} ${poppins.variable} ${greyQo.variable} ${dance.variable}`}
      >
        <AuthProvider>
          <Navbar />
          <main className="p-5">{children}</main>
          <MyFooter />
        </AuthProvider>
      </body>
    </html>
  );
}
